export const companyInformation = {
  name: 'BookDia Night',
  legalName: 'Beverly Group Srl',
  address: 'Via Sant’Anselmo, 34, 00153 Roma, Italy',
  email: 'support@bookdianight.com',
  phone: '+44 2045716412',
  website: 'https://bookdianight.com',
  logo: 'https://bookdianight-storage.fra1.cdn.digitaloceanspaces.com/attachments/dfea5cd3-1fce-4ad9-95ee-dd6dabfd37c1-1788236612997.png',
  copyright: `© ${new Date().getFullYear()} BookDia Night. All rights reserved.`,
};

export const emailInformation = {
  fromName: 'BookDia Night',
  fromEmail: 'no-reply@bookdianight.com',
  replyTo: 'support@bookdianight.com',
};

/**
 * ==============================================
 * ------------------QUEUE JOBS------------------
 * ==============================================
 * ⚠️ DEVELOPER NOTICE: AUTOGENERATED SECTION
 * Do not modify this section manually. It is automatically updated by the create:queue-job script.
 */
export const QUEUE_JOBS = {
  // AUTO-GENERATED-JOBS-START
  SIGNUP_USER_VERIFICATION_SUCCESSFUL: 'signup-user-verification-successful',
  SEND_SIGNUP_SUCCESS_EMAIL: 'send-signup-success-email',
  // AUTO-GENERATED-JOBS-END
} as const;
