services:
  db-migrator:
    image: ${DOCKER_USERNAME}/bookdianight-server:latest
    container_name: bookdianight-db-migrator
    env_file: .env
    command: ["npx", "prisma", "migrate", "deploy"]
    networks:
      - bookdianight-network
    restart: "no"
  scheduler:
    image: ${DOCKER_USERNAME}/bookdianight-scheduler:latest
    container_name: bookdianight-scheduler
    env_file: .env
    networks:
      - bookdianight-network
    depends_on:
      db-migrator:
        condition: service_completed_successfully
    restart: unless-stopped
  worker:
    image: ${DOCKER_USERNAME}/bookdianight-worker:latest
    container_name: bookdianight-worker
    env_file: .env
    networks:
      - bookdianight-network
    depends_on:
      db-migrator:
        condition: service_completed_successfully
    restart: unless-stopped
  server:
    image: ${DOCKER_USERNAME}/bookdianight-server:latest
    container_name: bookdianight-server
    env_file: .env
    ports:
      - 5000:5000
    networks:
      - bookdianight-network
    depends_on:
      db-migrator:
        condition: service_completed_successfully
    restart: unless-stopped
networks:
  bookdianight-network:
    driver: bridge
