FROM node:22-alpine AS base

WORKDIR /app

RUN apk add --no-cache dumb-init

COPY prisma.config.ts ./
COPY prisma ./prisma/

COPY corn/package*.json ./
COPY corn/tsconfig.json ./

COPY scheduler/ ./

COPY corn/ ./

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "dev"]