/**
 * ==============================================
 * ------------------QUEUE JOBS------------------
 * ==============================================
 * ⚠️ DEVELOPER NOTICE: AUTOGENERATED SECTION
 * Do not modify this section manually. It is automatically updated by the create:queue-job script.
 */
export const QUEUE_JOBS = {
  // AUTO-GENERATED-JOBS-START
  SEND_SIGNUP_SUCCESS_EMAIL: 'send-signup-success-email',
  // AUTO-GENERATED-JOBS-END
} as const;
