/**
 * ==============================================
 * ------------------QUEUE JOBS------------------
 * ==============================================
 * ⚠️ DEVELOPER NOTICE: AUTOGENERATED SECTION
 * Do not modify this section manually. It is automatically updated by the create:queue-job script.
 */
export const QUEUE_JOBS = {
  // AUTO-GENERATED-JOBS-START
  RECOVER_USER_PASSWORD_RESET_SUCCESSFUL:
    'recover-user-password-reset-successful',
  RECOVER_USER_VERIFICATION_OTP: 'recover-user-verification-otp',
  RESEND_VERIFICATION_OTP: 'resend-verification-otp',
  SIGNUP_USER_VERIFICATION_SUCCESSFUL: 'signup-user-verification-successful',
  SEND_SIGNUP_SUCCESS_EMAIL: 'send-signup-success-email',
  // AUTO-GENERATED-JOBS-END
} as const;
