name: Build and Deploy

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Extract metadata (tags, labels) for Server
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: registry.digitalocean.com/bookdianight-registry/bookdianight-server

      - name: Build and push Server Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ${{ steps.meta-server.outputs.tags }},registry.digitalocean.com/bookdianight-registry/bookdianight-server:latest
          labels: ${{ steps.meta-server.outputs.labels }}

      - name: Extract metadata (tags, labels) for Scheduler
        id: meta-scheduler
        uses: docker/metadata-action@v5
        with:
          images: registry.digitalocean.com/bookdianight-registry/bookdianight-scheduler

      - name: Build and push Scheduler Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scheduler/Dockerfile
          push: true
          tags: ${{ steps.meta-scheduler.outputs.tags }},registry.digitalocean.com/bookdianight-registry/bookdianight-scheduler:latest
          labels: ${{ steps.meta-scheduler.outputs.labels }}

      - name: Extract metadata (tags, labels) for Worker
        id: meta-worker
        uses: docker/metadata-action@v5
        with:
          images: registry.digitalocean.com/bookdianight-registry/bookdianight-worker

      - name: Build and push Worker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./worker/Dockerfile
          push: true
          tags: ${{ steps.meta-worker.outputs.tags }},registry.digitalocean.com/bookdianight-registry/bookdianight-worker:latest
          labels: ${{ steps.meta-worker.outputs.labels }}

  deploy-to-droplet:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment on DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_HOST }}
          username: ${{ secrets.DO_DROPLET_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            export DOCKER_USERNAME=registry.digitalocean.com/bookdianight-registry
            # Authenticate the droplet to DigitalOcean Container Registry securely
            echo "${{ secrets.DO_REGISTRY_TOKEN }}" | docker login registry.digitalocean.com -u _ --password-stdin
            
            cd /opt/bookdianight-server
            # Make sure we pull the latest images
            docker compose pull
            # Start the stack (this triggers the migrator, then the scheduler)
            docker compose up -d

